version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/fuaad-portfolio"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "baseline-browser-mapping"

